sudo: required
language: python
git:
  depth: 10
  quiet: true
services:
  - docker
python:
  - "2.7"
  - "3.6"
env:
  global:
    - TF_LATEST="1.10.*"
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.
    # If updating, also update TF_LATEST above
    - TF_VERSION="1.9.*"
    - TF_VERSION="1.10.*"
    - TF_VERSION="tf-nightly"
matrix:
  exclude:
    # We test against all versions in Python 2 but only the latest in Python 3
    - python: "3.6"
      env: TF_VERSION="1.9.*"
    - python: "3.6"
      env: TF_VERSION="tf-nightly"
install:
  - ./oss_scripts/oss_pip_install.sh
script:
  - ./oss_scripts/oss_tests.sh
